services:
  velocity:
    image: itzg/mc-proxy:latest
    environment:
      - "TYPE=VELOCITY"
      - "DEBUG=false"
      - "MEMORY=1G"
    ports:
      - "25565:25565"
    volumes:
      - ./velocity:/server
    depends_on:
      - bot
    networks:
      - internal

  paper-1:
    image: itzg/minecraft-server
    environment:
      - "EULA=TRUE"
      - "ONLINE_MODE=FALSE"
      - "TYPE=PAPER"
      - "MEMORY=4G"
      - "SYNC_SKIP_NEWER_IN_DESTINATION=false"
    volumes:
      - ./paper:/data
    depends_on:
      - velocity
    networks:
      - internal
